Run Configure probes on physical iOS device

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -1505,7 +1505,7 @@ archname=''
 usereentrant='undef'
 : List of libraries we want.
 : If anyone needs extra -lxxx, put those in a hint file.
-libswanted="cl pthread socket bind inet nsl ndbm gdbm dbm db malloc dl ld"
+libswanted="cl pthread socket bind inet nsl ndbm dbm malloc dl ld"
 libswanted="$libswanted sun m crypt sec util c cposix posix ucb bsd BSD"
 : We probably want to search /usr/shlib before most other libraries.
 : This is only used by the lib/ExtUtils/MakeMaker.pm routine extliblist.
@@ -2330,7 +2330,7 @@ $define|true|[yY]*)
 
 EOH
 	rp='Do you really want to continue?'
-	dflt='n'
+		       dflt='y'
 	. ./myread
 	case "$ans" in
 	[yY]) echo >&4 "Okay, continuing."
@@ -3070,15 +3070,71 @@ case "$targethost" in
 	    from=$pwd/Cross/from
 	    ;;
 	esac
-	case "$targetrun" in
-	'') targetrun=ssh ;;
-	esac
-	case "$targetto" in
-	'') targetto=scp ;;
-	esac
-	case "$targetfrom" in
-	'') targetfrom=scp ;;
-	esac
+		case "$targetrun" in
+		darwin-ios)
+			: "${IOS_PLATFORM:=iphoneos}"
+			: "${IOS_ARCH:=arm64}"
+			: "${IOS_DEPLOYMENT_TARGET:=12.0}"
+			: "${IOS_SDKROOT:=$(xcrun --sdk "$IOS_PLATFORM" --show-sdk-path 2>/dev/null)}"
+			case "$IOS_SDKROOT" in
+			'') echo "Cannot determine the iOS SDK path; set IOS_SDKROOT." >&4
+				exit 1
+				;;
+			esac
+			case "$ccflags" in
+			*"-target "*) ;;
+			*) ccflags="$ccflags -target $IOS_ARCH-apple-ios$IOS_DEPLOYMENT_TARGET" ;;
+			esac
+			case "$ccflags" in
+			*"-isysroot "*) ;;
+			*) ccflags="$ccflags -isysroot $IOS_SDKROOT" ;;
+			esac
+			case "$ccflags" in
+			*"-miphoneos-version-min="*) ;;
+			*) ccflags="$ccflags -miphoneos-version-min=$IOS_DEPLOYMENT_TARGET" ;;
+			esac
+			case "$ccflags" in
+			*"-arch "*) ;;
+			*) ccflags="$ccflags -arch $IOS_ARCH" ;;
+			esac
+			case "$ldflags" in
+			*"-target "*) ;;
+			*) ldflags="$ldflags -target $IOS_ARCH-apple-ios$IOS_DEPLOYMENT_TARGET" ;;
+			esac
+			case "$ldflags" in
+			*"-isysroot "*) ;;
+			*) ldflags="$ldflags -isysroot $IOS_SDKROOT" ;;
+			esac
+			case "$ldflags" in
+			*"-miphoneos-version-min="*) ;;
+			*) ldflags="$ldflags -miphoneos-version-min=$IOS_DEPLOYMENT_TARGET" ;;
+			esac
+			case "$ldflags" in
+			*"-arch "*) ;;
+			*) ldflags="$ldflags -arch $IOS_ARCH" ;;
+			esac
+			export IOS_PLATFORM IOS_ARCH IOS_DEPLOYMENT_TARGET IOS_SDKROOT
+			;;
+		esac
+		case "$targetrun" in
+		'') targetrun=ssh ;;
+		darwin-ios)
+			: "${targetto:=cp}"
+			: "${targetfrom:=cp}"
+			;;
+		esac
+		case "$targetrun" in
+		darwin-ios)
+			targetto=cp
+			targetfrom=cp
+			;;
+		esac
+		case "$targetto" in
+		'') targetto=scp ;;
+		esac
+		case "$targetfrom" in
+		'') targetfrom=scp ;;
+		esac
 	run=$run-$targetrun
 	to=$to-$targetto
 	from=$from-$targetfrom
@@ -3102,6 +3158,10 @@ case "$targethost" in
 	*)	q='' ;;
 	esac
 	case "$targetrun" in
+		darwin-ios)
+			cp "$src/Cross/run-darwin-ios" "$run"
+			$chmod a+rx "$run"
+			;;
 	ssh|rsh)
 	    cat >$run <<EOF
 #!/bin/sh
@@ -3136,18 +3196,25 @@ EOF
 	    exit 1
 	    ;;
 	esac
-	case "$targetmkdir" in
-	*/Cross/mkdir)
+		case "$targetrun" in
+		darwin-ios)
+			:
+			;;
+		*)
+		case "$targetmkdir" in
+		*/Cross/mkdir)
 	    cat >$targetmkdir <<EOF
 #!/bin/sh
 $targetrun -p $targetport -l $targetuser $targethost "mkdir -p \$@"
 EOF
 	    $chmod a+rx $targetmkdir
 	    ;;
-	*)  echo "Unknown targetmkdir '$targetmkdir'" >&4
+		*)  echo "Unknown targetmkdir '$targetmkdir'" >&4
 	    exit 1
 	    ;;
 	esac
+		;;
+		esac
 	case "$targetto" in
 	scp|rcp)
 	    cat >$to <<EOF
@@ -4699,7 +4766,7 @@ int main(int argc, char **argv) {
 EOCP
 c99_for=no
 for flag in '' '-std=gnu99' '-std=c99'; do
-    if $cc -o try $flag $ccflags $ldflags try.c 2>/dev/null && ./try; then
+		 if $cc -o try $flag $ccflags $ldflags try.c 2>/dev/null && $run ./try; then
         c99_for="$flag"
         break;
     fi
@@ -4709,7 +4776,7 @@ case "$c99_for" in
     ;;
 no) echo >&4 "Your C compiler doesn't seem to be able to compile C99 code"
     rp='Do you really want to continue?'
-    dflt='n'
+			   dflt='y'
     . ./myread
     case "$ans" in
 	[yY])	echo >&4 "Okay, continuing."	;;
@@ -5715,8 +5782,9 @@ and I got the following output:
 EOM
 dflt=y
 if $sh -c "$cc -o try $optimize $ccflags $ldflags try.c $libs" >>try.msg 2>&1; then
-	if $sh -c "$run ./try " >>try.msg 2>&1; then
-		xxx=`$run ./try`
+	if $sh -c "$run ./try " >try.run 2>&1; then
+		$cat try.run >>try.msg
+		xxx=`$cat try.run`
 		case "$xxx" in
 		"Ok") dflt=n ;;
 		*)    echo 'The program compiled OK, but produced no output.' >> try.msg ;;
@@ -5724,7 +5792,7 @@ if $sh -c "$cc -o try $optimize $ccflags $ldflags try.c $libs" >>try.msg 2>&1; t
 	else
 		echo "The program compiled OK, but exited with status $?." >>try.msg
 		rp="You have a problem.  Shall I abort Configure"
-		dflt=y
+		dflt=n
 	fi
 else
 	echo "I can't compile the test program." >>try.msg
@@ -5751,7 +5819,7 @@ y)
 	;;
 n) echo "OK, that should do.";;
 esac
-$rm_try gcctest gcctest.out
+$rm_try gcctest gcctest.out try.run
 
 : define a shorthand compile call
 compile='
@@ -13380,6 +13448,11 @@ eval $setvar
 : see if fork exists
 set fork d_fork
 eval $inlibc
+case "$targetrun" in
+darwin-ios)
+	d_fork="$undef"
+	;;
+esac
 
 : see if pipe exists
 set pipe d_pipe
@@ -16158,7 +16231,7 @@ int main(int argc, char *argv[])
 }
 EOCP
 set try
-if eval $compile && ./try; then
+if eval $compile && $run ./try; then
     $echo "lchown() found." >&4
     val="$define"
 else
@@ -17478,6 +17551,12 @@ eval $setvar
 case "$d_vfork" in
 $define) usevfork='true';;
 *) usevfork='false';;
+esac
+case "$targetrun" in
+darwin-ios)
+	d_vfork="$undef"
+	usevfork='false'
+	;;
 esac
 
 : see whether the pthread_atfork exists
@@ -19763,11 +19842,21 @@ eval $inlibc
 : see if syscall exists
 set syscall d_syscall
 eval $inlibc
+case "$targetrun" in
+darwin-ios)
+	d_syscall="$undef"
+	;;
+esac
 
 : see if prototype for syscall is available
 echo " "
 set d_syscallproto syscall $i_unistd unistd.h
 eval $hasproto
+case "$targetrun" in
+darwin-ios)
+	d_syscallproto="$undef"
+	;;
+esac
 
 : see if sysconf exists
 set sysconf d_sysconf
